// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYcmAOrknq2J2Vz8GOs8umOEVO7kju5O0',
    appId: '1:319068265185:web:208f99ea382668b1f2b5a0',
    messagingSenderId: '319068265185',
    projectId: 'keys-5bf5e',
    authDomain: 'keys-5bf5e.firebaseapp.com',
    storageBucket: 'keys-5bf5e.appspot.com',
    measurementId: 'G-G8E6LEFEKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6RG-Cz902-QRDefq0a-9A6Rvqcxe5BR8',
    appId: '1:319068265185:android:73338f3277f01bc0f2b5a0',
    messagingSenderId: '319068265185',
    projectId: 'keys-5bf5e',
    storageBucket: 'keys-5bf5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3j3gIGXaBiOZYb2ojCDzcdVXhkbD5baE',
    appId: '1:319068265185:ios:bfd6bb33f9655110f2b5a0',
    messagingSenderId: '319068265185',
    projectId: 'keys-5bf5e',
    storageBucket: 'keys-5bf5e.appspot.com',
    iosClientId: '319068265185-dhgujvsslecr2ncaf9j2v576ptc3deos.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3Keys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3j3gIGXaBiOZYb2ojCDzcdVXhkbD5baE',
    appId: '1:319068265185:ios:698292c618c83300f2b5a0',
    messagingSenderId: '319068265185',
    projectId: 'keys-5bf5e',
    storageBucket: 'keys-5bf5e.appspot.com',
    iosClientId: '319068265185-ild9h2ruiut4lgr13ijud778sdusddmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3Keys.RunnerTests',
  );
}
